# Generated by Django 3.0.7 on 2020-06-25 21:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=127)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200000)])),
                ('bike_style', models.CharField(choices=[('NK', '네이키드'), ('RL', '레플리카'), ('AM', '아메리칸'), ('SC', '스쿠터'), ('TL', '투어링'), ('EL', '전기'), ('CM', '상업용'), ('AT', 'ATV'), ('OL', '오프로드'), ('MI', '포켓/미니')], max_length=2)),
                ('deal_area', models.CharField(choices=[('SU', '서울'), ('BS', '부산'), ('IC', '인천'), ('GJ', '광주'), ('US', '울산'), ('DJ', '대전'), ('SJ', '세종'), ('DG', '대구'), ('GG', '경기'), ('GW', '강원'), ('GN', '경남'), ('GB', '경북'), ('CB', '충북'), ('CN', '충남'), ('JB', '전북'), ('JN', '전남'), ('JJ', '제주')], max_length=2)),
                ('model_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('driven_distance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000000)])),
                ('document_status', models.CharField(choices=[('U', '준비되지않음'), ('R', '준비됨'), ('N', '없음')], default=None, max_length=1, null=True)),
                ('repair_history', models.TextField(max_length=2047, null=True)),
                ('tuning_history', models.TextField(max_length=2047, null=True)),
                ('detail_information', models.TextField(max_length=2047)),
                ('crawled_url', models.URLField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikePaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.BooleanField(default=False)),
                ('cash', models.BooleanField(default=False)),
                ('loan', models.BooleanField(default=False)),
                ('trade', models.BooleanField(default=False)),
                ('lease', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='buyk/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_image', to='bikes.Bike')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bikes.BikePaymentMethod'),
        ),
        migrations.AddField(
            model_name='bike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
