# Generated by Django 3.0.7 on 2020-06-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='crawled_url',
        ),
    ]
